### PR TITLE
add constraint component IRIs to SANode

### PR DESCRIPTION
**Pull request by lucascool12**
Draft for adding constraint components to SANodes.
Contains breaking change for TEST Op.

### CODE REVIEW

**Comment by MaximeJakubowski** [comment]
Thanks, this looks good. It is indeed a good idea to replace the strings in the Op.TEST with the constraint component names. This makes it more maintainable as well (not using my made up string names but using the SHACL IRIs). 

It is also natural to insert the constraint component names into the SANodes. This is roughly what I also had in mind. However, the reason this is not completely straightforward is because of the cleaning function in the utilities. In general, when we alter the SANode tree, it becomes unclear what constraint components we are actually working with. Could you elaborate a little on what your idea is there?

Ideally, it would be possible to reconstruct the SHACL shape from the SANode tree (or at least a close approximation). In the SHACL spec, the constraint components also always have "parameters". I think that, if we disregard the clean function, it is clear what the parameters are for each constraint component mentioned in the SANode tree. Ideally, it would still be clear after the clean function. My concern is more general: hopefully we can find a way to properly encode real SHACL constraint component information into the SANode tree, and it should be clear when altering the tree how to adjust this constraint component information. Do you have any thoughts on this?

**Comment by lucascool12** [comment]
> It is also natural to insert the constraint component names into the SANodes. This is roughly what I also had in mind. However, the reason this is not completely straightforward is because of the cleaning function in the utilities. In general, when we alter the SANode tree, it becomes unclear what constraint components we are actually working with. Could you elaborate a little on what your idea is there?

I didn't really put much thought into the changes I made in the cleaning function. I only changed it because when I tried it with only the changes in shapels.py none of the SANodes had a constraint component. But looking at it now I do see the problem most if not all of the ways a SANode might get cleaned up might lose information about constraint components. I think the easiest solution would be to add some parameter in the parse function to preserve the constraint components which would not run the cleaning function.

> Ideally, it would be possible to reconstruct the SHACL shape from the SANode tree (or at least a close approximation). In the SHACL spec, the constraint components also always have "parameters". I think that, if we disregard the clean function, it is clear what the parameters are for each constraint component mentioned in the SANode tree. Ideally, it would still be clear after the clean function. My concern is more general: hopefully we can find a way to properly encode real SHACL constraint component information into the SANode tree, and it should be clear when altering the tree how to adjust this constraint component information. Do you have any thoughts on this?

I'm unsure if it is possible to clean a SANode tree without losing information about the constraint components.
From a validator point of view there is no reason not to clean SANodes that would never result in a violation. But for other use cases that don't wanna lose information about constraint components even if they would never result in a violation, I think the only things you can safely clean without losing information are SANodes that don't have a constraint component. I don't think such SANodes get created.

**Comment by MaximeJakubowski** [comment]
I would not suggest adding an option to disable cleaning. This cleaning is important to remove some of the "side effects" of the way I translate shapes to the tree. However, now that I lookat it again, it seems most of your changes are probably not needed (in the clean function). Most of the places that you add the constraint information is in SANodes where Op is TOP or BOT. However, these never need constraint component information as they do not exist in real SHACL. The only place I can image that it is actually needed is where COUNTRANGEs are created. There, they do not need to inheret the constraint component of the original node, but they need to just get the corresponding constraint components (i.e. MinCountConstraintComponent or MaxCountConstraintComponent). 

Concretely, my suggestion would be to leave all constraint component information on None, except for the case in the cleaning function where Op is FORALL and COUNTRANGES are created. Do you agree?

**Comment by lucascool12** [comment]
I agree but for the case where Op is OR or AND and there is only a single child I think this case should be skipped if the constraint component of the SANode is not None. Otherwise it is possible for an OR or AND SANode with a constraint component to get optimized away with the clean function, example:
```turtle
@prefix ex: <http://example.org/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:TestShape a sh:NodeShape;
    sh:targetClass ex:Class;
    sh:or (
        [
            a sh:PropertyShape;
            sh:path ex:path;
            sh:minCount 1;
        ]
   ).
```
Becomes:
```
http://example.org/TestShape

(Op.HASSHAPE  cc=None  rdflib.term.BNode('nf6e01d092de142aa9b38e7ccea84d0b2b1'))
nf6e01d092de142aa9b38e7ccea84d0b2b1

(Op.COUNTRANGE  cc=http://www.w3.org/ns/shacl#MinCountConstraintComponent  rdflib.term.Literal('1', datatype=rdflib.term.URIRef('http://www.w3.org/2001/XMLSchema#integer'))
 None
 
 (POp.PROP  rdflib.term.URIRef('http://example.org/path'))
 
 (Op.TOP  cc=None))
```
The existence of the or constraint in ex:TestShape has been erased.

**Comment by MaximeJakubowski** [comment]
Good point, the cleaning function should distinguish between SANode constructs originating from my translation algorithm and SANode constructs that are inherent to the structure used in the shapes graph. This is an interesting topic to keep in mind for other aspects as well. Ideally, I want the slsparser to keep as much information about the original shapes graph as possible, while still parsing to the logical syntax. So, one of the ideas I had was to create different "optimization" functions that take a SANode tree, and produce a "simpler" one depending on the topic. For example, if you only care about the logical meaning of a shape, you should optimize away your example; there is no need for the OR. However, if you care about what was actually written (to, for example, recreate the shapes graph) then it may be useful to keep it. I have other applications of SHACL shapes (not necessarily involving conformance checking) where this is important.

All this is to say that you're right, and the clean function should not clean if there is a constraint component specified.

**Comment by lucascool12** [comment]
Does something along the lines of this look good?
The tests currently fail since I have not changed them yet.

**Comment by MaximeJakubowski** [comment]
So the idea is that if full is true, then the clean function does not try to simplify the parse tree if it has a constraint component specified with it. I think it would be ok to put the default value of full to True. 

There is one slight mistake I think in the parse function. The SH.ClassConstraintComponent should be set on the level of the COUNTRANGE, not on the level of the HASVALUE (around line 253). Do you agree? The whole construct is meant to model the class constraint component.

**Comment by lucascool12** [comment]
> There is one slight mistake I think in the parse function. The SH.ClassConstraintComponent should be set on the level of the COUNTRANGE, not on the level of the HASVALUE (around line 253). Do you agree? The whole construct is meant to model the class constraint component.

After thinking about it for a while I agree that the SH.ClassContraintComponent should be set on the COUNTRANGE.

**Comment by lucascool12** [comment]
I'll change the README and tests so they reflect the changes made to the TEST Op and then I think the pull request is ready to be merged.

**Comment by lucascool12** [comment]
Alright, the README and tests now also reflect the changes made.

**Pull request merged**
